<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            font-size: 20px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        h2 {
            color: #719e40;
        }

        ul {
            list-style: none; /* Remove default bullets */
        }

        ul li::before {
            content: "\2022"; /* Add content: \2022 is the CSS Code/unicode for a bullet */
            color: red; /* Change the color */
            font-weight: bold; /* If you want it to be bold */
            display: inline-block; /* Needed to add space between the bullet and the text */
            width: 1em; /* Also needed for space (tweak if needed) */
            margin-left: -1em; /* Also needed for space (tweak if needed) */
        }

    </style>
</head>
<body>

<h2><span class="label label-default">NSFW API (Not suitable for work classifier)</span></h2>

<hr/>
<h2><span class="label label-default">How to use it?</span></h2>
<br/>
<code>

    curl -X POST
    http://nsfw.ibra-node.com/api/detect-nsfw
    -H 'accept: application/json'
    -F 'files[]=@/Users/ibraheemabukaff/Desktop/test.jpg'

</code>

<hr/>
<h2><span class="label label-default">Response<span></h2>
<br/>
<script src="https://gist.github.com/ibraAbuKaff/b0bb1d980b332e83264f1c98bff83f41.js"></script>

<hr/>
<h2>Rules</h2>

<div class="alert alert-info" role="alert">Maximum 3 Images Per Request</div>
<div class="alert alert-info" role="alert">Max image size is 3MB</div>
<div class="alert alert-info" role="alert">Currently, the api is processing JPEG|JPG images</div>
<div class="alert alert-info" role="alert">We delete your uploaded images after we run our classifier against them</div>




</body>
</html>
