<!DOCTYPE html>
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129075289-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-129075289-1');
    </script>

    <meta charset="utf-8"/>
    <title>NSFW Classifier API</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            font-size: 20px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        h2 {
            color: #719e40;
        }


    </style>
</head>
<body>


<div class="jumbotron">
    <h1>Not suitable for work classifier</h1>
    <h2><span class="label label-default">NSFW API</span></h2>
    <p>
        Detecting offensive / adult images is an important problem which researchers have tackled for decades. With the evolution of computer vision and deep learning the algorithms have matured and we are now able to classify an image as not suitable for work with greater precision.
    </p>
</div>


<hr/>
<h2><span class="label label-default">How to use it?</span></h2>
<br/>
<code>

    curl -X POST
    http://nsfw.ibra-node.com/api/detect-nsfw
    -H 'accept: application/json'
    -F 'files[]=@/Users/ibraheemabukaff/Desktop/test.jpg'

</code>

<hr/>

<h2><span class="label label-default">Rules</span></h2>
<br/>
<ul class="list-group">
    <li class="list-group-item">
        Maximum 3 Images Per Request
    </li>

    <li class="list-group-item">
        Max image size is 3MB
    </li>

    <li class="list-group-item">
        Currently, the api is processing JPEG|JPG images
    </li>

    <li class="list-group-item">
        We delete your uploaded images after we run our classifier against them
    </li>
</ul>

<h2><span class="label label-default">Response<span></h2>
<br/>
<script src="https://gist.github.com/ibraAbuKaff/b0bb1d980b332e83264f1c98bff83f41.js"></script>

</body>
</html>
